language: node_js
node_js:
  - "7.10"

cache: 
  yarn: true
  directories:
  - node_modules

branches:
  only:
    - develop

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod

deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  skip_cleanup: true
  on:
    branch: develop

notifications:
  email:
    on_failure: change
    on_success: change